name: hackkosice2020
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  url_launcher: ^5.4.0 
  flutter:
    sdk: flutter

dependency_overrides:
  url_launcher: '5.4.0'


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Black.ttf
        - asset: fonts/Montserrat-BlackItalic.ttf
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-BoldItalic.ttf
        - asset: fonts/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat-ExtraBoldItalic.ttf
        - asset: fonts/Montserrat-ExtraLight.ttf
        - asset: fonts/Montserrat-ExtraLightItalic.ttf
        - asset: fonts/Montserrat-Italic.ttf
        - asset: fonts/Montserrat-Light.ttf
        - asset: fonts/Montserrat-LightItalic.ttf
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-MediumItalic.ttf
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-SemiBold.ttf
        - asset: fonts/Montserrat-SemiBoldItalic.ttf
        - asset: fonts/Montserrat-Thin.ttf
        - asset: fonts/Montserrat-ThinItalic.ttf
    
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Black.ttf
          weight: 900
        - asset: fonts/Nunito-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Nunito-Bold.ttf
          weight: 700
        - asset: fonts/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: fonts/Nunito-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: fonts/Nunito-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Nunito-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Nunito-Light.ttf
          weight: 300
        - asset: fonts/Nunito-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Nunito-Regular.ttf
          weight: 400
        - asset: fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: fonts/Nunito-SemiBoldItalic.ttf
          weight: 600
          style: italic







  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add fonts to your application, add an fonts section, like this:
  # fonts:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/fonts-and-images/#resolution-aware.

  # For details regarding adding fonts from package dependencies, see
  # https://flutter.dev/fonts-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
